CREATE TABLE `vasudeve_nft_project`.`nfts` (
    `id` INT NOT NULL,
    `keyboardKind` VARCHAR(5) NOT NULL,
    `keyboardType` VARCHAR(3) NOT NULL,
    `keyboardFilter` VARCHAR(10) NOT NULL,
    `ownerAddress` VARCHAR(42) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARSET = utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT = 'Holds NFT data for users';

CREATE TABLE table_name (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inserted_at timestamp with time zone DEFAULT timezone('utc' :: text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc' :: text, now()) NOT NULL,
    `keyboardKind` text NOT NULL,
    `keyboardType` text NOT NULL,
    `keyboardFilter` text NOT NULL,
    `ownerAddress` text NOT NULL
);